### ISSUE TITLE
oss-parent 依赖从哪里来哈

### ISSUE THREAD

**Issue by keyofwork** [minbox-projects/api-boot#1]
Project build error: Non-resolvable parent POM for org.minbox.framework:api-boot:0.1.1.RELEASE: Failure to find org.minbox.framework:oss-parent:pom:0.1.0.RELEASE in http://
 maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are 
 forced and 'parent.relativePath' points at wrong local POM

**Comment by hengboy** [comment]
@keyofwork 这个依赖是api-boot用于发布maven center中央仓库的依赖，已经在maven center内，路径：https://repo.maven.apache.org/maven2/org/minbox/framework/
如果无法下载，请先通过clone https://github.com/hengboy/oss-parent 到本地后install
