### ISSUE TITLE
无法导入相应包

### ISSUE THREAD

**Issue by Cyberhan123** [minbox-projects/api-boot#11]
![image](https://user-images.githubusercontent.com/38837039/62450219-7fe5e780-b79e-11e9-8524-fd133e3d9538.png)
下面是我的maven配置,maven的依赖没保存，但是就是导入不了包。请指教！

> @Cyberhan123 具体是什么问题？添加完版本依赖后，刷新项目了吗？

刷新了
![image](https://user-images.githubusercontent.com/38837039/62450722-6f823c80-b79f-11e9-9656-12604f500531.png)

**Comment by hengboy** [comment]
@Cyberhan123 具体是什么问题？添加完版本依赖后，刷新项目了吗？

**Comment by Cyberhan123** [comment]
emmm我发个截图吧

**Comment by hengboy** [comment]
应该是没有下载完成`api-boot`相关的`jar`，你可以将本地`maven`仓库的相关`api-boot`的文件夹删掉，通过`idea`的maven reimport重新下载`api-boot`依赖

**Comment by Cyberhan123** [comment]
我发现问题：
```
<dependencyManagement>
    <dependencies>
        <!--ApiBoot版本依赖-->
        <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>api-boot-dependencies</artifactId>
            <version>{lastVersion}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
```
这个给了我误导，没仔细看{lastVersion}的解释，导致我直接粘贴使用没查询最新版。哈哈哈

**Comment by hengboy** [comment]
嗯`api-boot-dependencies`是版本依赖，添加版本依赖后`api-boot`相关的所有`starter`就不用添加版本号了。
