### ISSUE TITLE
2.1.3.RELEASE jar下载不了

### ISSUE THREAD

**Issue by neiyou** [minbox-projects/api-boot#14]
在pom里配置了2.1.3.RELEASE    却下载不了。
2.1.2可下载

 <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Finchley.M9</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			
			<dependency>
				<groupId>org.minbox.framework</groupId>
				<artifactId>api-boot-dependencies</artifactId>
				<version>2.1.3.RELEASE</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by hengboy** [comment]
@neiyou 不好意思，2.1.3.RELEASE版本出现点问题，请暂时使用**2.1.4-SNAPSHOT**，修改你项目`pom.xml`如下所示：
```
<dependencyManagement>
    <dependencies>
        <!--ApiBoot版本依赖-->
        <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>api-boot-dependencies</artifactId>
            <version>2.1.4-SNAPSHOT</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
<repositories>
    <repository>
        <id>Snapshots</id>
        <name>ApiBoot Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
    <repository>
        <id>central</id>
        <name>Maven Repository Switchboard</name>
        <url>https://maven.aliyun.com/repository/public</url>
        <releases>
            <enabled>true</enabled>
        </releases>
    </repository>
</repositories>
```

**Comment by hengboy** [comment]
@neiyou 针对这个问题，使用上面快照版本也可以，昨天新发布了**2.1.4-RC1**版本也是可以的。
