### ISSUE TITLE
Quartz执行updateJobCron出错

### ISSUE THREAD

**Issue by 282919088** [minbox-projects/api-boot#16]
api-boot-starter-quartz  
版本：2.1.4.RELEASE
Quartz执行updateJobCron出错，提示
(ApiBootQuartzServiceDefaultSupport.java:225)
org.quartz.impl.triggers.SimpleTriggerImpl cannot be cast to org.quartz.CronTrigger

**Comment by hengboy** [comment]
@282919088 可以先去看下官网文档，http://apiboot.minbox.io/zh-cn/docs/api-boot-quartz.html ，如果问题还不能解决，麻烦把具体的控制台异常使用```形式贴出来

**Comment by 282919088** [comment]
还是不可以，不知道是不是版本问题，我的springboot是2.1.8.RELEASE版本
`2019-10-07 18:39:26.677 [http-nio-8080-exec-5] ERROR o.m.f.a.b.p.q.s.ApiBootQuartzServiceDefaultSupport - Update job cron error.
java.lang.ClassCastException: org.quartz.impl.triggers.SimpleTriggerImpl cannot be cast to org.quartz.CronTrigger
	at org.minbox.framework.api.boot.plugin.quartz.support.ApiBootQuartzServiceDefaultSupport.updateJobCron(ApiBootQuartzServiceDefaultSupport.java:225)
	at com.nsc.boot.core.quartz.interfaces.JobInterfaces.updateJobCron(JobInterfaces.java:74)`

**Comment by hengboy** [comment]
@282919088 相同jobKey的任务是不是存在多个不同类型的？比如once、cron、loop三种类型的任务都是使用同样的jobKey？

**Comment by 282919088** [comment]
@hengboy  是我的失误，Loop 类型的用updateJobCron去修改了，感谢你的解惑。

**Comment by hengboy** [comment]
@282919088 不客气，有问题随时可以提交issues
