### ISSUE TITLE
想问下数据库的sql 在哪儿

### ISSUE THREAD

**Issue by 704480904** [minbox-projects/api-boot#2]
想问下数据库的sql 在哪儿

**Comment by hengboy** [comment]
ApiBoot Security 内置读取用户表的sql？
还是Oauth2的？

**Comment by 704480904** [comment]
就是里面的数据库  url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai

**Comment by hengboy** [comment]
这是我本地测试的，你可以更换为你自己的数据库信息
具体使用访问：https://github.com/hengboy/api-boot/tree/master/api-boot-samples/api-boot-sample-security-oauth-jwt

**Comment by 704480904** [comment]
![image](https://user-images.githubusercontent.com/6984303/54670945-c7414380-4b2f-11e9-8944-3ff2f16bb9c0.png)
