### ISSUE TITLE
spring-boot2.3.1版本引入apiboot-swagger问题

### ISSUE THREAD

**Issue by Aaron-Lfg** [minbox-projects/api-boot#20]
1. springboot2.3.x的版本把validation从spring-boot-starter-web内移出来了，需要单独依赖javax.validation
2.不引入apiboot-oauth2，swagger-ui页面还是会需要有认证

**Comment by hengboy** [comment]
SpringBoot在2.3.x分支版本的`spring-boot-starter-web`依赖内删除了`spring-boot-starter-validation`，在项目中添加该依赖即可，如下所示：
```xml
<!--After SpringBoot 2.3.x version, need to add this dependency-->
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
```

**Comment by hengboy** [comment]
该问题在`ApiBoot v2.2.6`之后的版本会修复
