### ISSUE TITLE
接口长时间不用，再次请求接口会报 hikariPool 相关错误

### ISSUE THREAD

**Issue by Jack0971** [minbox-projects/api-boot#52]
错误内容如下：
HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@589a8f9a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by hengboy** [comment]
@Jack0971 由于`spring-boot-starter-jdbc`默认依赖了`HikariCP`数据源，在项目启动时会对它进行一些初始化，已经做出了修改，排除了默认数据源

**Comment by hengboy** [comment]
使用方式请参考：https://github.com/minbox-projects/api-boot/blob/2.3.x/api-boot-samples/api-boot-sample-datasource-switch/pom.xml

**Comment by hengboy** [comment]
`2.3.1-SNAPSHOT`版本才支持这种方式，如果不着急可以等`2.3.1.RELEASE`正式发版

**Comment by Jack0971** [comment]
@hengboy 我项目不急呀，等着新版出来

**Comment by hengboy** [comment]
@Jack0971 好的，那你点击项目右上角的`Watch`，选择`Release Only`，发布版本时就会给你推送邮件了
