### ISSUE TITLE
对于限流问题

### ISSUE THREAD

**Issue by PlayTaoist** [minbox-projects/api-boot#7]
我看到项目有限流功能，觉得这个项目很有用处。不过我有以下几个问题
1.限流是限制所有的IP嘛(就是一个接口做了限流然后这个接口就只能1秒访问20次)；如果出现大并发情况又想限流怎么办？
2.可不可以指定限流的IP或者IP段，这样可以避免某些程序自动循环调用接口。

**Comment by hengboy** [comment]
@PlayTaoist 目前ApiBoot RateLimiter配置接口限流后，是对所有IP请求进行限流，后期可以添加自定义限流方式来解决部分IP或者IP段进行限流，应对于突发状况的流量激增，ApiBoot RateLimiter提供了Nacos配置中心的方式来实时更新运行期间的每一个接口的QPS值，注意项目重启后会覆盖掉Nacos配置中心内的数据。

**Comment by hengboy** [comment]
具体怎么使用Nacos Config 来支持配置QPS详见文档，地址：http://apiboot.yuqiyu.com/docs/apiboot-rate-limiter.html

**Comment by PlayTaoist** [comment]
谢谢文档已经收藏。正在关注此项目，后面如果有需要会尝试加入项目中

**Comment by hengboy** [comment]
@PlayTaoist 可以的，ApiBoot欢迎开发人员成为代码贡献者，有需求也可以提建议
